spring:
  application:
    name: gateway-service
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - gateway
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
server:
  port: 8072


